### ISSUE TITLE
Only DM the user once when they join

### ISSUE THREAD

**Issue by yeSpud** [uaf-cs/nookbot#4]
<img width="977" alt="Screen Shot 2020-03-12 at 16 25 51" src="https://user-images.githubusercontent.com/10385195/76576057-3bca6c00-647e-11ea-9ab0-e2061fae9f26.png">

**Comment by yeSpud** [comment]
#1

**Comment by yeSpud** [comment]
emphasis on **ONCE**

**Comment by theGordHoard** [comment]
This issue can be closed as we no longer DM users on join at all.
